import os
import httpx
import asyncio
from datetime import datetime, timedelta
from typing import List, Dict
from sqlalchemy.orm import Session
from app.models.learning import ClassSummary, StudentNote
from app.models.cohort import GroupClass, GroupClassStatus
from fastapi import HTTPException

# Read credentials from environment (reusing existing variables)
GROQ_API_KEY = os.getenv("FASTAPI_GROK_API_KEY")
GROQ_URL = os.getenv("FASTAPI_GROK_API_URL")
GROQ_MODEL = os.getenv("FASTAPI_GROK_MODEL")

def chunk_transcript(dialogue_log: List[Dict], max_words: int = 1500) -> List[str]:
    """
    Groups individual dialogue log entries into text chunks of approximately max_words
    to prevent context overflow with the GPT OSS 20B model.
    """
    chunks = []
    current_chunk = []
    current_word_count = 0

    for entry in dialogue_log:
        speaker = entry.get("speaker", "Speaker")
        text = entry.get("text", "")
        timestamp = entry.get("timestamp", "")
        if timestamp:
            # Extract HH:MM
            try:
                dt = datetime.fromisoformat(timestamp)
                time_str = dt.strftime("%H:%M")
            except Exception:
                time_str = timestamp[:5]
        else:
            time_str = "00:00"

        line = f"[{time_str}] {speaker}: {text}"
        words_in_line = len(line.split())

        if current_word_count + words_in_line > max_words and current_chunk:
            chunks.append("\n".join(current_chunk))
            current_chunk = [line]
            current_word_count = words_in_line
        else:
            current_chunk.append(line)
            current_word_count += words_in_line

    if current_chunk:
        chunks.append("\n".join(current_chunk))

    return chunks

async def call_llm_api(prompt: str) -> str:
    """
    Sends a query to the configured GPT OSS 20B / Groq endpoint.
    """
    if not GROQ_API_KEY or not GROQ_URL:
        print("[Summary Service Error] AI API credentials or URL missing.")
        return "AI summarization config missing on server."

    payload = {
        "model": GROQ_MODEL,
        "input": prompt
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                GROQ_URL,
                headers={
                    "Authorization": f"Bearer {GROQ_API_KEY}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=60.0
            )

            if response.status_code != 200:
                print(f"[Summary Service Error] LLM returned status {response.status_code}: {response.text}")
                return "Failed to generate summary from AI endpoint."

            data = response.json()
            generated_text = ""
            
            if "output" in data and isinstance(data["output"], list):
                message_obj = next(
                    (item for item in data["output"] if item.get("type") == "message"), 
                    None
                )
                if message_obj and "content" in message_obj and len(message_obj["content"]) > 0:
                    generated_text = message_obj["content"][0].get("text", "")

            return generated_text or "No text generated by AI."
        except Exception as e:
            print(f"[Summary Service Error] Exception during LLM call: {e}")
            return f"Error communicating with AI service: {str(e)}"

async def generate_summary(db: Session, group_class_id: int, dialogue_log: List[Dict]):
    """
    Main background workflow to chunk, summarize, and save a class summary.
    """
    if not dialogue_log:
        print(f"[Summary Service] No dialogue logged for class {group_class_id}. Skipping summary.")
        return

    print(f"[Summary Service] Generating summary for class {group_class_id} (log size: {len(dialogue_log)})")
    
    # 1. Chunk transcript if it is long
    chunks = chunk_transcript(dialogue_log, max_words=1500)
    chunk_summaries = []

    # 2. Summarize each chunk
    for idx, chunk in enumerate(chunks):
        prompt = (
            f"You are a JavaScript course assistant. Summarize this segment (Part {idx + 1}) "
            f"of the live class transcript below. Focus on key explanations, answers to student doubts, "
            f"and important concepts discussed. Do NOT output code snippets yet; just extract critical takeaways.\n\n"
            f"TRANSCRIPT SEGMENT:\n{chunk}"
        )
        summary = await call_llm_api(prompt)
        chunk_summaries.append(summary)

    # 3. Synthesize final markdown notes summary
    combined_summaries_text = "\n\n".join(
        [f"### Part {i+1} Takeaways\n{s}" for i, s in enumerate(chunk_summaries)]
    )

    final_synthesis_prompt = (
        f"You are a Senior JavaScript Instructor. Below are segment summaries of today's live group class lecture. "
        f"Synthesize them into a single, cohesive, highly professional Markdown study note sheet for the students. "
        f"Ensure it contains the following sections:\n"
        f"1. ## 📅 Live Class Summary: Topic Name\n"
        f"2. ### 💡 Core Concepts & Takeaways (summarized into clear bullet points)\n"
        f"3. ### ❓ Mid-Class Doubts & Clarifications (reconstruct any student Q&As or doubts solved by the trainer during the session)\n"
        f"4. ### 💻 Conceptual Code Examples (write clean, syntax-highlighted JS code blocks demonstrating what was taught)\n\n"
        f"SEGMENT SUMMARIES:\n{combined_summaries_text}"
    )

    final_markdown_summary = await call_llm_api(final_synthesis_prompt)

    # 4. Save to Database
    expires_at = datetime.utcnow() + timedelta(days=2)
    summary_record = ClassSummary(
        group_class_id=group_class_id,
        content=final_markdown_summary,
        expires_at=expires_at
    )
    db.add(summary_record)
    
    # Also mark class as COMPLETED in DB if not already done
    group_class = db.query(GroupClass).filter(GroupClass.id == group_class_id).first()
    if group_class:
        group_class.status = GroupClassStatus.COMPLETED
        
    db.commit()
    print(f"[Summary Service] Successfully cached summary for class {group_class_id}. Expires at {expires_at.isoformat()}")

    # 5. Broadcast notification to the cohort students via Socket.IO
    try:
        from app.routers.signaling import sio
        from app.models.student import Student
        
        if group_class:
            students = db.query(Student).filter(Student.cohort_id == group_class.cohort_id).all()
            for s in students:
                await sio.emit("class_summary_ready", {
                    "class_id": group_class_id,
                    "summary_id": summary_record.id,
                    "topic": group_class.topic,
                    "title": group_class.title,
                    "expires_in_hours": 48
                }, room=f"global_user_{s.user_id}")
            print(f"[Summary Service] Dispatched notifications to {len(students)} cohort students.")
    except Exception as notify_err:
        print(f"[Summary Service] Notification broadcast failed: {notify_err}")
